language: python
matrix:
    include:
        - python: 3.8
        - python: 3.8
          arch: arm64

install:
  - sudo apt-get install graphviz
  - "python setup.py install"
  - "pip install nose coverage coveralls"
  - "pip install isort pycodestyle pydocstyle"
  - "pip list"

script:
  - nosetests
 
